<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-BackgroundAssistant-14af64a3-5408-49ce-ac61-834bb806cc04</UserSecretsId>
    <!-- 啟用 Native AOT 優化記憶體 -->
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <!-- 啟用 Workstation GC 優先節省記憶體 (針對 4GB 上限環境) -->
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
    <!-- 核心推論引擎 -->
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.20.1" /> <!-- 若有 GPU -->
    <PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.DirectML" Version="0.6.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="org.k2fsa.sherpa.onnx" Version="1.10.*" />
    <PackageReference Include="org.k2fsa.sherpa.onnx.runtime.win-x64" Version="1.10.*" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="10.0.8" />
    <PackageReference Include="TinyPinyin.Net" Version="1.0.2" />
  </ItemGroup>
</Project>
